services:
  - type: web
    name: stream-one
    env: python
    plan: free
    build:
      pythonVersion: "3.10"
    buildCommand: |
      apt-get update && apt-get install -y python3-distutils
      pip install -r requirements.txt
    startCommand: python3 app.py
