services:
  - type: web
    name: stream-one
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y python3-distutils
      pip install -r requirements.txt
    startCommand: python app.py
